-- Supabase SQL Editorで実行
create table if not exists profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  rank_points integer not null default 0,
  coins integer not null default 0,
  weapon_level integer not null default 1,
  hp_level integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists friendships(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(user_id, friend_id)
);

alter table profiles enable row level security;
alter table friendships enable row level security;

create policy "profiles read" on profiles for select to authenticated using(true);
create policy "profiles own insert" on profiles for insert to authenticated with check(auth.uid() = id);
create policy "profiles own update" on profiles for update to authenticated using(auth.uid() = id) with check(auth.uid() = id);

create policy "friends read own" on friendships for select to authenticated using(auth.uid() = user_id or auth.uid() = friend_id);
create policy "friends insert own" on friendships for insert to authenticated with check(auth.uid() = user_id);
create policy "friends update involved" on friendships for update to authenticated using(auth.uid() = user_id or auth.uid() = friend_id);

alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table friendships;
